# SPDX-FileCopyrightText: 2023 Jeff Epler for Adafruit Industries
# SPDX-License-Identifier: MIT

[defaults]
sizes = [6, 8, 9, 10, 11, 12, 14, 18, 24, 30, 36, 42, 48, 54, 60, 72, 84, 96, 108, 120, 144]

# Note that subset ranges are *inclusive* of the upper bound in otf2bdf
[variants]
#ascii = "32_126"
latin1 = "32_255"

# [FONT.FontFileNameWithoutExtension]
# name = "desired_package_base_name"
