# SPDX-FileCopyrightText: 2023 Jeff Epler for Adafruit Industries
# SPDX-License-Identifier: MIT

[defaults]
sizes = [6, 8, 10, 12, 14, 18, 24, 30, 36, 42, 48, 54, 60, 72]

# Note that subset ranges are *inclusive* of the upper bound in otf2bdf
[variants]
#ascii = "32_126"
latin1 = "32_255"

# [FONT.FontFileNameWithoutExtension]
# name = "desired_package_base_name"
# filename = "relative/path/to/font_file.ttf_or_otf
# license = "LICENSES/license-name.txt"
